// packages/angular/src/components/barcode.component.ts
import {
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
  ViewChild,
} from '@angular/core'
import type { BarcodeConfig, BarcodeFormat, BarcodeInstance } from '@ldesign/barcode-core'
import { createBarcode } from '@ldesign/barcode-core'

@Component({
  selector: 'ldesign-barcode',
  standalone: true,
  template: `<div #barcodeContainer class="ldesign-barcode"></div>`,
  styles: [`
    .ldesign-barcode {
      display: inline-block;
    }
  `],
})
export class BarcodeComponent implements OnInit, OnChanges, OnDestroy {
  @ViewChild('barcodeContainer', { static: true }) container!: ElementRef<HTMLDivElement>

  @Input({ required: true }) content!: string
  @Input() format?: BarcodeFormat
  @Input() width = 200
  @Input() height = 100
  @Input() displayValue = true
  @Input() background = '#ffffff'
  @Input() foreground = '#000000'
  @Input() renderType: 'svg' | 'canvas' = 'canvas'
  @Input() margin = 10
  @Input() fontSize = 14
  @Input() textAlign: 'left' | 'center' | 'right' = 'center'
  @Input() fontFamily = 'monospace'
  @Input() lineWidth = 2

  private barcodeInstance: BarcodeInstance | null = null

  ngOnInit(): void {
    this.renderBarcode()
  }

  ngOnChanges(changes: SimpleChanges): void {
    // 如果已经初始化且有变化，重新渲染
    if (this.barcodeInstance && !changes['content']?.firstChange) {
      this.renderBarcode()
    }
  }

  ngOnDestroy(): void {
    this.destroyBarcode()
  }

  private renderBarcode(): void {
    // 销毁旧实例
    this.destroyBarcode()

    // 创建新实例
    const config: BarcodeConfig = {
      content: this.content,
      format: this.format,
      width: this.width,
      height: this.height,
      displayValue: this.displayValue,
      background: this.background,
      foreground: this.foreground,
      renderType: this.renderType,
      margin: this.margin,
      fontSize: this.fontSize,
      textAlign: this.textAlign,
      fontFamily: this.fontFamily,
      lineWidth: this.lineWidth,
      container: this.container.nativeElement,
    }

    try {
      this.barcodeInstance = createBarcode(config)
    }
    catch (error) {
      console.error('Failed to create barcode:', error)
    }
  }

  private destroyBarcode(): void {
    if (this.barcodeInstance) {
      this.barcodeInstance.destroy()
      this.barcodeInstance = null
    }
  }

  /**
   * 下载条形码
   */
  download(fileName?: string, format?: 'png' | 'jpeg' | 'svg'): void {
    if (this.barcodeInstance) {
      this.barcodeInstance.download(fileName, format)
    }
  }

  /**
   * 获取DataURL
   */
  toDataURL(format: 'png' | 'jpeg' = 'png', quality?: number): string | null {
    if (this.barcodeInstance) {
      try {
        return this.barcodeInstance.toDataURL(format, quality)
      }
      catch {
        return null
      }
    }
    return null
  }

  /**
   * 获取SVG字符串
   */
  toSVGString(): string | null {
    if (this.barcodeInstance) {
      try {
        return this.barcodeInstance.toSVGString()
      }
      catch {
        return null
      }
    }
    return null
  }
}

// packages/svelte/src/components/Barcode.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { BarcodeConfig, BarcodeFormat, BarcodeInstance } from '@ldesign/barcode-core'
  import { createBarcode } from '@ldesign/barcode-core'

  // Props
  export let content: string
  export let format: BarcodeFormat | undefined = undefined
  export let width = 200
  export let height = 100
  export let displayValue = true
  export let background = '#ffffff'
  export let foreground = '#000000'
  export let renderType: 'svg' | 'canvas' = 'canvas'
  export let margin = 10
  export let fontSize = 14
  export let textAlign: 'left' | 'center' | 'right' = 'center'
  export let fontFamily = 'monospace'
  export let lineWidth = 2

  let container: HTMLDivElement
  let instance: BarcodeInstance | null = null

  function renderBarcode() {
    // 销毁旧实例
    if (instance) {
      instance.destroy()
      instance = null
    }

    // 创建新实例
    const config: BarcodeConfig = {
      content,
      format,
      width,
      height,
      displayValue,
      background,
      foreground,
      renderType,
      margin,
      fontSize,
      textAlign,
      fontFamily,
      lineWidth,
      container,
    }

    try {
      instance = createBarcode(config)
    }
    catch (error) {
      console.error('Failed to create barcode:', error)
    }
  }

  // 导出方法
  export function download(fileName?: string, exportFormat?: 'png' | 'jpeg' | 'svg') {
    if (instance) {
      instance.download(fileName, exportFormat)
    }
  }

  export function toDataURL(exportFormat: 'png' | 'jpeg' = 'png', quality?: number): string | null {
    if (instance) {
      try {
        return instance.toDataURL(exportFormat, quality)
      }
      catch {
        return null
      }
    }
    return null
  }

  export function toSVGString(): string | null {
    if (instance) {
      try {
        return instance.toSVGString()
      }
      catch {
        return null
      }
    }
    return null
  }

  onMount(() => {
    renderBarcode()
  })

  onDestroy(() => {
    if (instance) {
      instance.destroy()
      instance = null
    }
  })

  // 响应式更新
  $: if (container && instance) {
    renderBarcode()
  }
</script>

<div bind:this={container} class="ldesign-barcode" />

<style>
  .ldesign-barcode {
    display: inline-block;
  }
</style>
