// packages/react/src/components/BarcodeScanner.tsx
/**
 * React BarcodeScanner component
 */

import React, { useRef, useState, ChangeEvent } from 'react';
import { BarcodeFormat, ScannerOptions, ScanResult } from '../../../types';
import { useBarcodeScanner } from '../hooks/useBarcodeScanner';

export interface BarcodeScannerProps {
  formats?: BarcodeFormat[];
  preprocess?: boolean;
  maxAttempts?: number;
  multiple?: boolean;
  onScan?: (results: ScanResult[]) => void;
  onError?: (error: Error) => void;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * BarcodeScanner Component
 */
export const BarcodeScanner: React.FC<BarcodeScannerProps> = ({
  formats,
  preprocess = true,
  maxAttempts = 3,
  multiple = false,
  onScan,
  onError,
  className,
  style,
}) => {
  const options: ScannerOptions = {
    formats,
    preprocess,
    maxAttempts,
  };

  const { results, isScanning, error, scanFile, scanBatch } = useBarcodeScanner(options);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  /**
   * Trigger file input
   */
  const triggerFileInput = () => {
    fileInputRef.current?.click();
  };

  /**
   * Handle file change
   */
  const handleFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);

    if (files.length === 0) return;

    // Create preview
    if (files.length === 1) {
      setPreviewUrl(URL.createObjectURL(files[0]));
    }

    try {
      if (files.length === 1) {
        const scanResults = await scanFile(files[0]);
        onScan?.(scanResults);
      } else {
        const batchResults = await scanBatch(files);
        // Flatten batch results
        const allResults = batchResults.flatMap(br => br.results);
        onScan?.(allResults);
      }
    } catch (err) {
      onError?.(err as Error);
    }
  };

  /**
   * Cleanup preview URL
   */
  const cleanupPreview = () => {
    if (previewUrl) {
      URL.revokeObjectURL(previewUrl);
      setPreviewUrl(null);
    }
  };

  return (
    <div className={`barcode-scanner ${className || ''}`} style={{ ...defaultStyle, ...style }}>
      <div style={inputContainerStyle}>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          multiple={multiple}
          onChange={handleFileChange}
          style={fileInputStyle}
        />
        <button
          onClick={triggerFileInput}
          disabled={isScanning}
          style={buttonStyle(isScanning)}
        >
          {isScanning ? 'Scanning...' : 'Select Image'}
        </button>
      </div>

      {previewUrl && (
        <div style={previewContainerStyle}>
          <img src={previewUrl} alt="Preview" style={previewImageStyle} />
        </div>
      )}

      {isScanning && (
        <div style={loadingStyle}>
          <div style={spinnerStyle}></div>
          <span>Scanning barcode...</span>
        </div>
      )}

      {error && (
        <div style={errorStyle}>
          {error.message}
        </div>
      )}

      {results.length > 0 && (
        <div style={resultsStyle}>
          <h3 style={resultsTitleStyle}>Scan Results:</h3>
          {results.map((result, index) => (
            <div key={index} style={resultItemStyle}>
              <div style={resultFormatStyle}>{result.format}</div>
              <div style={resultDataStyle}>{result.data}</div>
              <div style={resultConfidenceStyle}>
                Confidence: {(result.confidence * 100).toFixed(1)}%
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// Styles
const defaultStyle: React.CSSProperties = {
  padding: '16px',
  border: '1px solid #dcdfe6',
  borderRadius: '4px',
};

const inputContainerStyle: React.CSSProperties = {
  marginBottom: '16px',
};

const fileInputStyle: React.CSSProperties = {
  display: 'none',
};

const buttonStyle = (disabled: boolean): React.CSSProperties => ({
  padding: '8px 16px',
  background: disabled ? '#a0cfff' : '#409eff',
  color: 'white',
  border: 'none',
  borderRadius: '4px',
  cursor: disabled ? 'not-allowed' : 'pointer',
  fontSize: '14px',
});

const previewContainerStyle: React.CSSProperties = {
  marginBottom: '16px',
};

const previewImageStyle: React.CSSProperties = {
  maxWidth: '100%',
  maxHeight: '300px',
  border: '1px solid #dcdfe6',
  borderRadius: '4px',
};

const loadingStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  padding: '12px',
  background: '#f4f4f5',
  borderRadius: '4px',
};

const spinnerStyle: React.CSSProperties = {
  width: '16px',
  height: '16px',
  border: '2px solid #409eff',
  borderTopColor: 'transparent',
  borderRadius: '50%',
  animation: 'spin 0.6s linear infinite',
};

const errorStyle: React.CSSProperties = {
  padding: '12px',
  background: '#fef0f0',
  color: '#f56c6c',
  borderRadius: '4px',
  marginBottom: '16px',
};

const resultsStyle: React.CSSProperties = {
  marginTop: '16px',
};

const resultsTitleStyle: React.CSSProperties = {
  margin: '0 0 12px 0',
  fontSize: '16px',
  color: '#303133',
};

const resultItemStyle: React.CSSProperties = {
  padding: '12px',
  background: '#f4f4f5',
  borderRadius: '4px',
  marginBottom: '8px',
};

const resultFormatStyle: React.CSSProperties = {
  fontWeight: 600,
  color: '#409eff',
  marginBottom: '4px',
};

const resultDataStyle: React.CSSProperties = {
  fontFamily: 'monospace',
  fontSize: '14px',
  marginBottom: '4px',
};

const resultConfidenceStyle: React.CSSProperties = {
  fontSize: '12px',
  color: '#909399',
};

export default BarcodeScanner;

// src/adapters/vue/components/BarcodeScanner.vue
<template>
  <div class="barcode-scanner">
    <div class="scanner-input">
      <input ref="fileInput" type="file" accept="image/*" :multiple="multiple" @change="handleFileChange"
        class="file-input" />
      <button @click="triggerFileInput" class="scan-button" :disabled="isScanning">
        {{ isScanning ? 'Scanning...' : 'Select Image' }}
      </button>
    </div>

    <div v-if="previewUrl" class="preview-container">
      <img :src="previewUrl" alt="Preview" class="preview-image" />
    </div>

    <div v-if="isScanning" class="scanner-loading">
      <div class="spinner"></div>
      <span>Scanning barcode...</span>
    </div>

    <div v-if="error" class="scanner-error">
      {{ error.message }}
    </div>

    <div v-if="results.length > 0" class="scanner-results">
      <h3>Scan Results:</h3>
      <div v-for="(result, index) in results" :key="index" class="result-item">
        <div class="result-format">{{ result.format }}</div>
        <div class="result-data">{{ result.data }}</div>
        <div class="result-confidence">Confidence: {{ (result.confidence * 100).toFixed(1) }}%</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { BarcodeFormat, ScannerOptions } from '../../../types';
import { useBarcodeScanner } from '../composables/useBarcodeScanner';

// Props
interface Props {
  formats?: BarcodeFormat[];
  preprocess?: boolean;
  maxAttempts?: number;
  multiple?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  preprocess: true,
  maxAttempts: 3,
  multiple: false,
});

// Emits
const emit = defineEmits<{
  scan: [results: any[]];
  error: [error: Error];
}>();

// Scanner options
const options = computed<ScannerOptions>(() => ({
  formats: props.formats,
  preprocess: props.preprocess,
  maxAttempts: props.maxAttempts,
}));

// Use scanner composable
const { results, isScanning, error, scanFile, scanBatch } = useBarcodeScanner(options);

// File input ref
const fileInput = ref<HTMLInputElement | null>(null);
const previewUrl = ref<string | null>(null);

/**
 * Trigger file input
 */
const triggerFileInput = () => {
  fileInput.value?.click();
};

/**
 * Handle file change
 */
const handleFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const files = Array.from(target.files || []);

  if (files.length === 0) return;

  // Create preview
  if (files.length === 1) {
    previewUrl.value = URL.createObjectURL(files[0]);
  }

  try {
    if (files.length === 1) {
      const scanResults = await scanFile(files[0]);
      emit('scan', scanResults);
    } else {
      const batchResults = await scanBatch(files);
      emit('scan', batchResults);
    }
  } catch (err) {
    emit('error', err as Error);
  }
};

// Cleanup preview URL
const cleanupPreview = () => {
  if (previewUrl.value) {
    URL.revokeObjectURL(previewUrl.value);
    previewUrl.value = null;
  }
};

// Expose methods
defineExpose({
  scanFile,
  scanBatch,
  cleanupPreview,
});
</script>

<style scoped>
.barcode-scanner {
  padding: 16px;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
}

.scanner-input {
  margin-bottom: 16px;
}

.file-input {
  display: none;
}

.scan-button {
  padding: 8px 16px;
  background: #409eff;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
}

.scan-button:hover:not(:disabled) {
  background: #66b1ff;
}

.scan-button:disabled {
  background: #a0cfff;
  cursor: not-allowed;
}

.preview-container {
  margin-bottom: 16px;
}

.preview-image {
  max-width: 100%;
  max-height: 300px;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
}

.scanner-loading {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px;
  background: #f4f4f5;
  border-radius: 4px;
}

.spinner {
  width: 16px;
  height: 16px;
  border: 2px solid #409eff;
  border-top-color: transparent;
  border-radius: 50%;
  animation: spin 0.6s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.scanner-error {
  padding: 12px;
  background: #fef0f0;
  color: #f56c6c;
  border-radius: 4px;
  margin-bottom: 16px;
}

.scanner-results {
  margin-top: 16px;
}

.scanner-results h3 {
  margin: 0 0 12px 0;
  font-size: 16px;
  color: #303133;
}

.result-item {
  padding: 12px;
  background: #f4f4f5;
  border-radius: 4px;
  margin-bottom: 8px;
}

.result-format {
  font-weight: 600;
  color: #409eff;
  margin-bottom: 4px;
}

.result-data {
  font-family: monospace;
  font-size: 14px;
  margin-bottom: 4px;
}

.result-confidence {
  font-size: 12px;
  color: #909399;
}
</style>
