// packages/svelte/src/components/Barcode.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { BarcodeConfig, BarcodeFormat, BarcodeInstance } from '@ldesign/barcode-core'
  import { createBarcode } from '@ldesign/barcode-core'

  // Props
  export let content: string
  export let format: BarcodeFormat | undefined = undefined
  export let width = 200
  export let height = 100
  export let displayValue = true
  export let background = '#ffffff'
  export let foreground = '#000000'
  export let renderType: 'svg' | 'canvas' = 'canvas'
  export let margin = 10
  export let fontSize = 14
  export let textAlign: 'left' | 'center' | 'right' = 'center'
  export let fontFamily = 'monospace'
  export let lineWidth = 2

  let container: HTMLDivElement
  let instance: BarcodeInstance | null = null

  function renderBarcode() {
    // 销毁旧实例
    if (instance) {
      instance.destroy()
      instance = null
    }

    // 创建新实例
    const config: BarcodeConfig = {
      content,
      format,
      width,
      height,
      displayValue,
      background,
      foreground,
      renderType,
      margin,
      fontSize,
      textAlign,
      fontFamily,
      lineWidth,
      container,
    }

    try {
      instance = createBarcode(config)
    }
    catch (error) {
      console.error('Failed to create barcode:', error)
    }
  }

  // 导出方法
  export function download(fileName?: string, exportFormat?: 'png' | 'jpeg' | 'svg') {
    if (instance) {
      instance.download(fileName, exportFormat)
    }
  }

  export function toDataURL(exportFormat: 'png' | 'jpeg' = 'png', quality?: number): string | null {
    if (instance) {
      try {
        return instance.toDataURL(exportFormat, quality)
      }
      catch {
        return null
      }
    }
    return null
  }

  export function toSVGString(): string | null {
    if (instance) {
      try {
        return instance.toSVGString()
      }
      catch {
        return null
      }
    }
    return null
  }

  onMount(() => {
    renderBarcode()
  })

  onDestroy(() => {
    if (instance) {
      instance.destroy()
      instance = null
    }
  })

  // 响应式更新
  $: if (container && instance) {
    renderBarcode()
  }
</script>

<div bind:this={container} class="ldesign-barcode" />

<style>
  .ldesign-barcode {
    display: inline-block;
  }
</style>

// packages/solid/src/components/Barcode.tsx
import { createEffect, createSignal, onCleanup, type Component } from 'solid-js'
import type { BarcodeConfig, BarcodeFormat, BarcodeInstance } from '@ldesign/barcode-core'
import { createBarcode } from '@ldesign/barcode-core'

export interface BarcodeProps {
  content: string
  format?: BarcodeFormat
  width?: number
  height?: number
  displayValue?: boolean
  background?: string
  foreground?: string
  renderType?: 'svg' | 'canvas'
  margin?: number
  fontSize?: number
  textAlign?: 'left' | 'center' | 'right'
  fontFamily?: string
  lineWidth?: number
}

export const Barcode: Component<BarcodeProps> = (props) => {
  let containerRef: HTMLDivElement | undefined
  let instance: BarcodeInstance | null = null
  const [error, setError] = createSignal<Error | null>(null)

  const renderBarcode = () => {
    if (!containerRef)
      return

    // 销毁旧实例
    if (instance) {
      instance.destroy()
      instance = null
    }

    // 创建新实例
    const config: BarcodeConfig = {
      content: props.content,
      format: props.format,
      width: props.width ?? 200,
      height: props.height ?? 100,
      displayValue: props.displayValue ?? true,
      background: props.background ?? '#ffffff',
      foreground: props.foreground ?? '#000000',
      renderType: props.renderType ?? 'canvas',
      margin: props.margin ?? 10,
      fontSize: props.fontSize ?? 14,
      textAlign: props.textAlign ?? 'center',
      fontFamily: props.fontFamily ?? 'monospace',
      lineWidth: props.lineWidth ?? 2,
      container: containerRef,
    }

    try {
      instance = createBarcode(config)
      setError(null)
    }
    catch (err) {
      setError(err as Error)
      console.error('Failed to create barcode:', err)
    }
  }

  createEffect(() => {
    // 监听props变化
    props.content
    renderBarcode()
  })

  onCleanup(() => {
    if (instance) {
      instance.destroy()
      instance = null
    }
  })

  return (
    <div>
      <div ref={containerRef} class="ldesign-barcode" />
      {error() && <div class="ldesign-barcode-error">错误: {error()!.message}</div>}
    </div>
  )
}

export default Barcode
