// packages/svelte/src/components/BarcodeScanner.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import type { BarcodeFormat, ScanResult, ScannerOptions } from '@ldesign/barcode-core'
  import { ImageScanner } from '@ldesign/barcode-core'

  // Props
  export let formats: BarcodeFormat[] | undefined = undefined
  export let preprocess = true
  export let maxAttempts = 3
  export let showInput = true

  const dispatch = createEventDispatcher<{
    scan: ScanResult[]
    error: Error
    scanning: boolean
  }>()

  let fileInput: HTMLInputElement
  let scanner: ImageScanner | null = null
  let isScanning = false

  function initScanner() {
    const options: ScannerOptions = {
      formats,
      preprocess,
      maxAttempts,
    }

    scanner = new ImageScanner(options)
  }

  async function handleFileChange(event: Event) {
    const input = event.target as HTMLInputElement
    const files = input.files

    if (!files || files.length === 0)
      return

    isScanning = true
    dispatch('scanning', true)

    try {
      if (files.length === 1) {
        // 单个文件
        const results = await scanFile(files[0])
        dispatch('scan', results)
      }
      else {
        // 多个文件
        const batchResults = await scanBatch(Array.from(files))
        const allResults = batchResults.flatMap(r => r.results)
        dispatch('scan', allResults)
      }
    }
    catch (err) {
      dispatch('error', err as Error)
    }
    finally {
      isScanning = false
      dispatch('scanning', false)
      input.value = ''
    }
  }

  export async function scanFile(file: File): Promise<ScanResult[]> {
    if (!scanner) {
      throw new Error('Scanner not initialized')
    }

    return await scanner.scanFile(file)
  }

  export async function scanBatch(files: File[]): Promise<Array<{
    fileName: string
    results: ScanResult[]
    error?: Error
  }>> {
    if (!scanner) {
      throw new Error('Scanner not initialized')
    }

    return await scanner.scanBatch(files)
  }

  export function selectFile() {
    fileInput.click()
  }

  export function updateOptions(options: Partial<ScannerOptions>) {
    if (scanner) {
      scanner.setOptions(options)
    }
  }

  onMount(() => {
    initScanner()
  })
</script>

<div class="ldesign-barcode-scanner">
  <input
    bind:this={fileInput}
    type="file"
    accept="image/*"
    multiple
    on:change={handleFileChange}
    style:display={showInput ? 'block' : 'none'}
  />
  
  <div class="scanner-status">
    <slot {isScanning} />
  </div>
</div>

<style>
  .ldesign-barcode-scanner {
    display: block;
  }
  
  .scanner-status {
    margin-top: 1rem;
  }
</style>

// packages/angular/src/components/barcode-scanner.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core'
import type { BarcodeFormat, ScanResult, ScannerOptions } from '@ldesign/barcode-core'
import { ImageScanner } from '@ldesign/barcode-core'

@Component({
  selector: 'ldesign-barcode-scanner',
  standalone: true,
  template: `
    <div class="ldesign-barcode-scanner">
      <input
        #fileInput
        type="file"
        accept="image/*"
        multiple
        (change)="onFileChange($event)"
        [style.display]="showInput ? 'block' : 'none'"
      />
      <div class="scanner-status">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styles: [`
    .ldesign-barcode-scanner {
      display: block;
    }
    
    .scanner-status {
      margin-top: 1rem;
    }
  `],
})
export class BarcodeScannerComponent implements OnInit, OnDestroy {
  @ViewChild('fileInput', { static: true }) fileInput!: ElementRef<HTMLInputElement>

  @Input() formats?: BarcodeFormat[]
  @Input() preprocess = true
  @Input() maxAttempts = 3
  @Input() showInput = true

  @Output() scan = new EventEmitter<ScanResult[]>()
  @Output() error = new EventEmitter<Error>()
  @Output() scanning = new EventEmitter<boolean>()

  private scanner: ImageScanner | null = null

  ngOnInit(): void {
    this.initScanner()
  }

  ngOnDestroy(): void {
    this.scanner = null
  }

  private initScanner(): void {
    const options: ScannerOptions = {
      formats: this.formats,
      preprocess: this.preprocess,
      maxAttempts: this.maxAttempts,
    }

    this.scanner = new ImageScanner(options)
  }

  async onFileChange(event: Event): Promise<void> {
    const input = event.target as HTMLInputElement
    const files = input.files

    if (!files || files.length === 0)
      return

    this.scanning.emit(true)

    try {
      if (files.length === 1) {
        // 单个文件
        const results = await this.scanFile(files[0])
        this.scan.emit(results)
      }
      else {
        // 多个文件
        const batchResults = await this.scanBatch(Array.from(files))
        // 合并所有结果
        const allResults = batchResults.flatMap(r => r.results)
        this.scan.emit(allResults)
      }
    }
    catch (err) {
      this.error.emit(err as Error)
    }
    finally {
      this.scanning.emit(false)
      // 清空input以允许重复选择同一文件
      input.value = ''
    }
  }

  /**
   * 扫描单个文件
   */
  async scanFile(file: File): Promise<ScanResult[]> {
    if (!this.scanner) {
      throw new Error('Scanner not initialized')
    }

    return await this.scanner.scanFile(file)
  }

  /**
   * 批量扫描文件
   */
  async scanBatch(files: File[]): Promise<Array<{
    fileName: string
    results: ScanResult[]
    error?: Error
  }>> {
    if (!this.scanner) {
      throw new Error('Scanner not initialized')
    }

    return await this.scanner.scanBatch(files)
  }

  /**
   * 触发文件选择
   */
  selectFile(): void {
    this.fileInput.nativeElement.click()
  }

  /**
   * 更新扫描器选项
   */
  updateOptions(options: Partial<ScannerOptions>): void {
    if (this.scanner) {
      this.scanner.setOptions(options)
    }
  }
}
